#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i '/VoCore2/d' /etc/opkg/distfeeds.conf

if [ -n "$(grep 'root::' /etc/shadow)" ]; then
	sed -i -e 's/root::/root:$1$nClfHNjC$V458KFdeS8bMgeo1f15sM.:/g' /etc/shadow
fi


echo 'uci set wireless.sta.disabled=0' > /etc/rc.local
echo 'uci commit' >> /etc/rc.local
echo '/etc/init.d/network restart' >> /etc/rc.local
echo 'sleep 10' >> /etc/rc.local
echo 'uci set wireless.sta.disabled=1' >> /etc/rc.local
echo 'uci commit' >> /etc/rc.local
echo '# Put your custom commands here that should be executed once' >> /etc/rc.local
echo '# the system init finished. By default this file does nothing.' >> /etc/rc.local
echo  >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local

uci set system.@system[-1].hostname="vocore2"
uci set network.wwan=interface
uci set network.wwan.proto=dhcp

uci set system.led_wifi=led
uci set system.led_wifi.sysfs='VoCore2:pink:wifi'
uci set system.led_wifi.dev='apcli0'
uci set system.led_wifi.trigger='netdev'
uci set system.led_wifi.mode='link'
uci set system.led_wifi.name='WIFI'
uci set wireless.radio0.disabled='0'

uci delete wireless.default_radio0

if [ "$(uci -q get wireless.ap)" != "wifi-iface" ]; then
	uci set wireless.ap=wifi-iface
	uci set wireless.ap.device='radio0'
	uci set wireless.ap.mode='ap'
	uci set wireless.ap.network='lan'
	uci set wireless.ap.ifname='ra0'
	uci set wireless.ap.ssid='VoCore2'
	uci set wireless.ap.key='12345678'
	uci set wireless.ap.encryption='psk2'
	uci set wireless.ap.disabled='0'
fi

if [ "$(uci -q get wireless.sta)" != "wifi-iface" ]; then
	uci set wireless.sta=wifi-iface
	uci set wireless.sta.device='radio0'
	uci set wireless.sta.mode='sta'
	uci set wireless.sta.network='lan wwan'
	uci set wireless.sta.ifname='apcli0'
	uci set wireless.sta.ssid='UplinkAp'
	uci set wireless.sta.encryption='psk2'
	uci set wireless.sta.key='SecretKey'
	uci set wireless.sta.disabled='1'
fi
uci commit
